/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * Credits goes to all Open Source Core Developer Groups listed below
 * Please do not change here something, ragarding the developer credits, except the "developed by XXXX".
 * Even if you edit a lot of files in this source, you still have no rights to call it as "your Core".
 * Everybody knows that this Emulator Core was developed by Aion Lightning 
 * @-Aion-Unique-
 * @-Aion-Lightning
 * @Aion-Engine
 * @Aion-Extreme
 * @Aion-NextGen
 * @Aion-Core Dev.
 */
package com.aionemu.gameserver.skillengine.effect;

/**
 * @author kecimis
 */
public enum EffectType {

    ABSOLUTESLOW,
    ABSOLUTESNARE,
    ABSOLUTESTATTOPCBUFF,
    ABSOLUTESTATTOPCDEBUFF,
    ACTIVATEENSLAVE,
    ALWAYSBLOCK,
    ALWAYSDODGE,
    ALWAYSPARRY,
    ALWAYSRESIST,
    APBOOST,
    ARMORMASTERY,
    AURA,
    BACKDASH,
    FRONTDASH,
    BIND,
    BLEED,
    BLIND,
    BOOSTDROPRATE,
    BOOSTHATE,
    BOOSTHEAL,
    BOOSTSKILLCASTINGTIME,
    BOOSTSKILLCOST,
    BOOSTSPELLATTACK,
    BUFFBIND,
    BUFFSILENCE,
    BUFFSLEEP,
    BUFFSTUN,
    CANNON,
    CARVESIGNET,
    CASEHEAL,
    CHANGEHATEONATTACKED,
    CLOSEAERIAL,
    CONDSKILLLAUNCHER,
    CONFUSE,
    CONVERTHEAL,
    CURSE,
    DASH,
    DEATHBLOW,
    DEBOOSTHEAL,
    DEFORM,
    DELAYEDFPATKINSTANT,
    DELAYEDSKILL,
    DELAYEDSPELLATTACKINSTANT,
    DISEASE,
    DISPEL,
    DISPELBUFF,
    DISPELBUFFCOUNTERATK,
    DISPELDEBUFF,
    DISPELDEBUFFMENTAL,
    DISPELDEBUFFPHYSICAL,
    DISPELNPCBUFF,
    DISPELNPCDEBUFF,
    DPHEAL,
    DPHEALINSTANT,
    DPTRANSFER,
    DRBOOST,
    DUMMY,
    ESCAPE,
    EVADE,
    EXTENDAURARANGE,
    FALL,
    FEAR,
    FLYOFF,
    FPATTACK,
    FPATTACKINSTANT,
    FPHEAL,
    FPHEALINSTANT,
    HEAL,
    HEALCASTORONATTACKED,
    HEALCASTORONTARGETDEAD,
    HEALINSTANT,
    HIDE,
    HIPASS,
    HOSTILEUP,
    INTERVALSKILL,
    INVULNERABLEWING,
    MAGICCOUNTERATK,
    MOVEBEHIND,
    MPATTACK,
    MPATTACKINSTANT,
    MPHEAL,
    MPHEALINSTANT,
    MPSHIELD,
    NODEATHPENALTY,
    NOFLY,
    NOREDUCESPELLATKINSTANT,
    NORESURRECTPENALTY,
    ONETIMEBOOSTHEAL,
    ONETIMEBOOSTSKILLATTACK,
    ONETIMEBOOSTSKILLCRITICAL,
    OPENAERIAL,
    PARALYZE,
    PETORDERUSEULTRASKILL,
    PETRIFICATION,
    POISON,
    POLYMORPH,
    PROCATKINSTANT,
    PROCDPHEALINSTANT,
    PROCFPHEALINSTANT,
    PROCHEALINSTANT,
    PROCMPHEALINSTANT,
    PROCVPHEALINSTANT,
    PROTECT,
    PROVOKER,
    PULLED,
    RANDOMMOVELOC,
    REBIRTH,
    RECALLINSTANT,
    REFLECTOR,
    RESURRECT,
    RESURRECTBASE,
    RESURRECTPOSITIONAL,
    RETURN,
    RETURNPOINT,
    RIDEROBOT,
    ROOT,
    SANCTUARY,
    SEARCH,
    SHAPECHANGE,
    SHIELD,
    SHIELDMASTERY,
    SIGNET,
    SIGNETBURST,
    SILENCE,
    SIMPLEROOT,
    SKILLATKDRAININSTANT,
    SKILLATTACKINSTANT,
    SKILLCOOLTIMERESET,
    SKILLLAUNCHER,
    SKILLXPBOOST,
    SLEEP,
    SLOW,
    SNARE,
    SPELLATTACK,
    SPELLATKDRAIN,
    SPELLATKDRAININSTANT,
    SPELLATTACKINSTANT,
    SPIN,
    STAGGER,
    STATBOOST,
    STATDOWN,
    STATUP,
    STUMBLE,
    STUN,
    SUBTYPEBOOSTRESIST,
    SUBTYPEEXTENDDURATION,
    SUMMON,
    SUMMONBINDINGGROUPGATE,
    SUMMONFUNCTIONALNPC,
    SUMMONGROUPGATE,
    SUMMONHOMING,
    SUMMONHOUSEGATE,
    SUMMONSERVANT,
    SUMMONSKILLAREA,
    SUMMONTOTEM,
    SUMMONTRAP,
    SWITCHHOSTILE,
    SWITCHHPMP,
    TARGETTELEPORT,
    WEAPONSTATBOOST,
    WEAPONSTATUP,
    WEAPONDUAL,
    WEAPONMASTERY,
    XPBOOST,
    STUNALWAYS,
    DELAYEDSKILL2
}
